author: kuangpengfei # ä½œè€…
description: bolg
keyword: vuejs
favicon: 
title: KuangPFğŸ––blog

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: true

# comment
# you can set gitment or uyan


comment: gitment

# gitment config
gitment_owner: KuangPF
gitment_repo: bolg
gitment_oauth_id: b72ce2d9cb2b8c5175a5
gitment_oauth_secret: ed963635170152c37f7c7c087049f00d01055b6c


# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars2.githubusercontent.com/u/20694238?s=460&v=4
  description: äººç”Ÿä¸åªæœ‰çœ¼å‰çš„è‹Ÿä¸”ï¼Œè¿˜æœ‰è¯—å’Œè¿œæ–¹.
  # Links
  weibo_username: kuangpf
  facebook_username: kuangpf
  github_username: KuangPF
  zhihu_username: KuangPF
  mail_username: cgi-bin/qm_share?t=qm_mailme&email=qpucmZmZk52Ykpzq29uEycXH