author: kuangpengfei # ä½œè€…
description: bolg
keyword: vuejs
favicon: 
title: KuangPFğŸ––blog
logoTitle: FE

excerpt_link: Read more

menu:
 é¦–é¡µ: /
 æ ‡ç­¾: /tags/
 å½’æ¡£: /archives/
 å¼€æºé¡¹ç›®: /project/
 å…³äº: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: true

# comment
# you can set gitment or uyan


comment: gitment

# gitment config
gitment_owner: KuangPF
gitment_repo: bolg
gitment_oauth_id: b72ce2d9cb2b8c5175a5
gitment_oauth_secret: ed963635170152c37f7c7c087049f00d01055b6c


# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars2.githubusercontent.com/u/20694238?s=460&v=4
  description: å…¶å®ï¼Œæ•²ä»£ç ä¸æ˜¯çˆ±å¥½ï¼Œä¹Ÿè®¸...
  # Links
	segmentfault_username: kuangpengfei
  weibo_username: kuangpf
  facebook_username: kuangpf
  github_username: KuangPF
  zhihu_username: KuangPF
  mail_username: cgi-bin/qm_share?t=qm_mailme&email=qpucmZmZk52Ykpzq29uEycXH